
{
	request: "api/categories/3/0/articles",
	id: 3,
	clang: 0,
	pid: 3,
	re_id: 0,
	name: "Referenzen",
	prior: 1,
	attributes: "",
	startpage: 1,
	path: "|",
	createdate: 1280159918,
	updatedate: 1544285487,
	template_id: 1,
	createuser: "Thomas",
	updateuser: "Thomas",
	revision: 0,
	link: "https://www.kuehne-webdienste.de/api/categories/3/0",
	categories: [
		{
			id: 12,
			clang: 0,
			pid: 12,
			re_id: 3,
			name: "Shuri Ryu Berlin",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1404049179,
			updatedate: 1543838561,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/12/0/articles",
			articles: [
				{
					id: 12,
					clang: 0,
					pid: 12,
					re_id: 12,
					name: "Shuri Ryu Berlin",
					catname: "Shuri Ryu Berlin",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1404049179,
					updatedate: 1543838561,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		},
		{
			id: 7,
			clang: 0,
			pid: 7,
			re_id: 3,
			name: "Tangará Brasil",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1280159902,
			updatedate: 1486048701,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/7/0/articles",
			articles: [
				{
					id: 7,
					clang: 0,
					pid: 7,
					re_id: 7,
					name: "Tangará Brasil",
					catname: "Tangará Brasil",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1280159902,
					updatedate: 1486048701,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		},
		{
			id: 11,
			clang: 0,
			pid: 11,
			re_id: 3,
			name: "Coach Concept ICTD GmbH",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1548690666,
			updatedate: 1423763495,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/11/0/articles",
			articles: [
				{
					id: 11,
					clang: 0,
					pid: 11,
					re_id: 11,
					name: "Coach Concept ICTD GmbH",
					catname: "Coach Concept ICTD GmbH",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1548690666,
					updatedate: 1423763495,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		},
		{
			id: 13,
			clang: 0,
			pid: 13,
			re_id: 3,
			name: "Moldt Events",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1404049185,
			updatedate: 1410461900,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/13/0/articles",
			articles: [
				{
					id: 13,
					clang: 0,
					pid: 13,
					re_id: 13,
					name: "Moldt Events",
					catname: "Moldt Events",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1404049185,
					updatedate: 1410461900,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		},
		{
			id: 8,
			clang: 0,
			pid: 8,
			re_id: 3,
			name: "Samspel e. V.",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1548690670,
			updatedate: 1486048563,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/8/0/articles",
			articles: [
				{
					id: 8,
					clang: 0,
					pid: 8,
					re_id: 8,
					name: "Samspel e. V.",
					catname: "Samspel e. V.",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1548690670,
					updatedate: 1486048563,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		},
		{
			id: 65,
			clang: 0,
			pid: 68,
			re_id: 3,
			name: "EasySpeedo App",
			prior: 1,
			attributes: "",
			startpage: 1,
			path: "|3|",
			createdate: 1548690671,
			updatedate: 1515251069,
			template_id: 13,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			link: "https://www.kuehne-webdienste.de/api/categories/65/0/articles",
			articles: [
				{
					id: 65,
					clang: 0,
					pid: 68,
					re_id: 65,
					name: "EasySpeedo App",
					catname: "EasySpeedo App",
					attributes: "",
					startpage: 1,
					prior: 1,
					path: "|3|",
					createdate: 1548690671,
					updatedate: 1515251069,
					template_id: 13,
					createuser: "Thomas",
					updateuser: "Thomas",
					revision: 0,
					metainfos: {
						art_online_from: "",
						art_online_to: "",
						art_description: "",
						art_keywords: "",
						art_file: "",
						art_teaser: "",
						art_type_id: "",
						art_showtitle: "normal"
					}
				}
			]
		}
	],
	articles: [
		{
			id: 3,
			clang: 0,
			pid: 3,
			re_id: 3,
			name: "Referenzen, Auswahl",
			catname: "Referenzen",
			attributes: "",
			startpage: 1,
			prior: 1,
			path: "|",
			createdate: 1280159918,
			updatedate: 1544285487,
			template_id: 1,
			createuser: "Thomas",
			updateuser: "Thomas",
			revision: 0,
			metainfos: {
				art_online_from: "",
				art_online_to: "",
				art_description: "",
				art_keywords: "",
				art_file: "",
				art_teaser: "",
				art_type_id: "",
				art_showtitle: "normal"
			}
		}
	]
}
